### ISSUE TITLE
Typings wrong, also not marked in package.json

### ISSUE THREAD

**Issue by timvahlbrock** [borisgontar/osm-pbf-parser-node#1]
Hi, I tried to use you library from typescript, but the typings seem to be wrong. `createOSMStream` returns void, but from the example you provide it should return an Iterator. Additionally, the availability of types is not marked in the package.json in the `typings` field.

**Comment by borisgontar** [comment]
Please check if the following changes make it usable for you. I don't use typescript myself.

```
export async function* createOSMStream(file: string, opts?: OSMOptions): 
  AsyncGenerator<object, void, unknown>;
export function parse(osmdata: Buffer, transform: OSMTransform|OSMOptions): Array<object>;
```

**Comment by timvahlbrock** [comment]
Your's works, but produces some warning by the TypeScript Compiler. This should be the right version:

```ts
declare module 'osm-pbf-parser-node' {
    import { Transform, TransformOptions } from 'node:stream';

    type WithTags = boolean | string[];

    export interface OSMOptions {
        withTags?: boolean | { node?: WithTags, way?: WithTags, relation?: WithTags },
        withInfo?: boolean,
        writeRaw?: boolean
    }

    export class OSMTransform extends Transform {
        constructor(osmopts?: OSMOptions, opts?: TransformOptions);
    }

    export function createOSMStream(file: string, opts?: OSMOptions): AsyncGenerator<object, void, unknown>;
    export function parse(osmdata: Buffer, transform: OSMTransform | OSMOptions): Array<object>;
}
```

**Comment by timvahlbrock** [comment]
And, as you are using the Buffer Type, you will have to add "@types/node", which defines it, to the dev dependencies.

**Comment by timvahlbrock** [comment]
BTW: if I call `createOSMStream` on a large file, I will still get a "Maximum call stack size exceeded" error, which defeats the purpose of using a stream...

**Comment by borisgontar** [comment]
Can you give me a link to that large file?

**Comment by timvahlbrock** [comment]
https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf

**Comment by borisgontar** [comment]
Works for me using my simple test,js:
```
$ node test.js 2 nordrhein-westfalen-latest.osm.pbf
reading from nordrhein-westfalen-latest.osm.pbf
withInfo: false, withTags: {"node":["name","amenity","shop"],"way":[],"relation":["boundary"
]}
header: seqno: 3897, timestamp: 07 Dec 2023 21:21:32 GMT, url: http://download.geofabrik.de/
europe/germany/nordrhein-westfalen-updates
counted: 80157377 nodes, 13337831 ways, 140286 relations
         1348515 items/sec.
elapsed: 1:09.437 (m:ss.mmm)
```
Can you create a small test to help me to reproduce the problem?

**Comment by timvahlbrock** [comment]
Sorry, I gave you the wrong url. I tried it using this one: https://download.bbbike.org/osm/bbbike/Bochum/Bochum.osm.pbf , thought they were from the same source, but aren't.

**Comment by timvahlbrock** [comment]
Tried it again with the file I sent yesterday, works fine.

**Comment by borisgontar** [comment]
The problem reproduced, hope to fix soon.

**Comment by borisgontar** [comment]
Fixed in 1.1.2, please try again.

**Comment by timvahlbrock** [comment]
> Fixed in 1.1.2, please try again.

The errors mentioned in https://github.com/borisgontar/osm-pbf-parser-node/issues/1#issuecomment-1847095381 are still present (and should definitely by fixed), but the call stack size error is gone. Type-Definition reference in package.json looks good as well.

**Comment by borisgontar** [comment]
I thought that typescript was already happy with the latest version of d.ts file. What is the message now? Is it from tsc or from tslint?

**Comment by timvahlbrock** [comment]
It works, but the compiler isn't happy about it. It's basically about which syntax is allowed in the type definitions of libraries (e.g. marking a function as async as redundant, because all that matters to the consuming code is that the function returns a promise). This checking can be disabled in the tsconfig (using skipLibCheck), but only on project level, not library level. I can send you the exact warnings later.

**Comment by timvahlbrock** [comment]
> Your's works, but produces some warning by the TypeScript Compiler. This should be the right version:
> 
> 
> 
> ```ts
> 
> declare module 'osm-pbf-parser-node' {
> 
>     import { Transform, TransformOptions } from 'node:stream';
> 
> 
> 
>     type WithTags = boolean | string[];
> 
> 
> 
>     export interface OSMOptions {
> 
>         withTags?: boolean | { node?: WithTags, way?: WithTags, relation?: WithTags },
> 
>         withInfo?: boolean,
> 
>         writeRaw?: boolean
> 
>     }
> 
> 
> 
>     export class OSMTransform extends Transform {
> 
>         constructor(osmopts?: OSMOptions, opts?: TransformOptions);
> 
>     }
> 
> 
> 
>     export function createOSMStream(file: string, opts?: OSMOptions): AsyncGenerator<object, void, unknown>;
> 
>     export function parse(osmdata: Buffer, transform: OSMTransform | OSMOptions): Array<object>;
> 
> }
> 
> ```

These changes mitigate the warnings.

**Comment by borisgontar** [comment]
Please use 1.1.3, an ugly misprint was fixed. The index.d.ts is now your code.
